export interface AnimalSprite {
  name: string;
  nameKo: string;
  pixels: string[][];
  color: string;
}

const _ = '';
const O = 'fill';

export const ANIMALS: AnimalSprite[] = [
  {
    name: 'cat',
    nameKo: '고양이',
    color: '#f4a261',
    pixels: [
      [O,_,_,_,_,_,O],
      [O,O,_,_,_,O,O],
      [O,O,O,O,O,O,O],
      [O,'e',O,O,O,'e',O],
      [O,O,O,'n',O,O,O],
      [_,O,O,O,O,O,_],
      [_,_,O,O,O,_,_],
    ],
  },
  {
    name: 'dog',
    nameKo: '강아지',
    color: '#8d6e63',
    pixels: [
      [_,O,O,O,O,O,_],
      [O,O,O,O,O,O,O],
      [O,'e',O,O,O,'e',O],
      [O,O,O,'n',O,O,O],
      [O,O,O,O,O,O,O],
      [_,O,_,O,_,O,_],
      [O,O,_,_,_,O,O],
    ],
  },
  {
    name: 'rabbit',
    nameKo: '토끼',
    color: '#ffb6c1',
    pixels: [
      [_,O,_,_,_,O,_],
      [_,O,_,_,_,O,_],
      [_,O,_,_,_,O,_],
      [O,O,O,O,O,O,O],
      [O,'e',O,O,O,'e',O],
      [O,O,O,'n',O,O,O],
      [_,O,O,O,O,O,_],
    ],
  },
  {
    name: 'bird',
    nameKo: '새',
    color: '#64b5f6',
    pixels: [
      [_,_,O,O,O,_,_],
      [_,O,O,O,O,O,_],
      [O,O,'e',O,'e',O,O],
      [_,O,O,'b',O,O,_],
      [_,_,O,O,O,_,_],
      [_,O,O,O,O,O,_],
      [_,_,_,O,_,_,_],
    ],
  },
  {
    name: 'frog',
    nameKo: '개구리',
    color: '#66bb6a',
    pixels: [
      ['e',O,O,O,O,O,'e'],
      ['e',O,O,O,O,O,'e'],
      [O,O,O,O,O,O,O],
      [O,O,O,O,O,O,O],
      [O,_,O,O,O,_,O],
      [_,_,O,O,O,_,_],
      [_,_,_,_,_,_,_],
    ],
  },
  {
    name: 'penguin',
    nameKo: '펭귄',
    color: '#37474f',
    pixels: [
      [_,_,O,O,O,_,_],
      [_,O,O,O,O,O,_],
      [O,O,'e',O,'e',O,O],
      [O,'w','w','b','w','w',O],
      [O,O,'w','w','w',O,O],
      [_,O,'w','w','w',O,_],
      [_,_,O,_,O,_,_],
    ],
  },
  {
    name: 'bear',
    nameKo: '곰',
    color: '#a1887f',
    pixels: [
      [O,_,O,O,O,_,O],
      [O,_,O,O,O,_,O],
      [O,O,O,O,O,O,O],
      [O,'e',O,O,O,'e',O],
      [O,O,'n','n','n',O,O],
      [O,O,O,O,O,O,O],
      [_,O,O,O,O,O,_],
    ],
  },
  {
    name: 'fox',
    nameKo: '여우',
    color: '#ff7043',
    pixels: [
      [O,_,_,_,_,_,O],
      [O,O,_,_,_,O,O],
      [O,'w',O,O,O,'w',O],
      [O,'e','w','w','w','e',O],
      [_,O,'w','n','w',O,_],
      [_,_,'w','w','w',_,_],
      [_,_,_,O,_,_,_],
    ],
  },
  {
    name: 'hamster',
    nameKo: '햄스터',
    color: '#ffcc80',
    pixels: [
      [_,O,O,O,O,O,_],
      [O,O,O,O,O,O,O],
      [O,'n','e',O,'e','n',O],
      [O,O,O,O,O,O,O],
      [O,'w','w','n','w','w',O],
      [_,'w','w','w','w','w',_],
      [_,_,O,O,O,_,_],
    ],
  },
  {
    name: 'panda',
    nameKo: '판다',
    color: '#eeeeee',
    pixels: [
      ['e',_,O,O,O,_,'e'],
      ['e',_,O,O,O,_,'e'],
      [O,O,O,O,O,O,O],
      [O,'e',O,O,O,'e',O],
      [O,O,O,'e',O,O,O],
      [_,O,O,O,O,O,_],
      [_,_,O,O,O,_,_],
    ],
  },
  {
    name: 'owl',
    nameKo: '부엉이',
    color: '#8d6e63',
    pixels: [
      [_,O,O,O,O,O,_],
      [O,O,O,O,O,O,O],
      [O,'w','e','w','e','w',O],
      [O,'w','e','w','e','w',O],
      [_,O,O,'b',O,O,_],
      [_,O,'w',O,'w',O,_],
      [_,_,O,O,O,_,_],
    ],
  },
  {
    name: 'turtle',
    nameKo: '거북이',
    color: '#4caf50',
    pixels: [
      [_,_,O,O,O,_,_],
      [_,O,O,O,O,O,_],
      [O,O,'e',O,'e',O,O],
      [O,O,O,O,O,O,O],
      [O,'n',O,'n',O,'n',O],
      [_,O,O,O,O,O,_],
      [O,_,_,_,_,_,O],
    ],
  },
  {
    name: 'chick',
    nameKo: '병아리',
    color: '#ffee58',
    pixels: [
      [_,_,O,O,O,_,_],
      [_,O,O,O,O,O,_],
      [_,O,'e',O,'e',O,_],
      [_,O,O,'b',O,O,_],
      [O,O,O,O,O,O,O],
      [_,O,O,O,O,O,_],
      [_,_,O,_,O,_,_],
    ],
  },
  {
    name: 'whale',
    nameKo: '고래',
    color: '#42a5f5',
    pixels: [
      [_,_,_,O,_,_,_],
      [_,O,O,O,O,O,_],
      [O,O,O,O,O,O,O],
      [O,'e',O,O,O,'e',O],
      [O,O,O,O,O,O,O],
      [_,O,O,O,O,O,_],
      [O,_,_,_,_,_,O],
    ],
  },
  {
    name: 'monkey',
    nameKo: '원숭이',
    color: '#d4a373',
    pixels: [
      [_,O,O,O,O,O,_],
      [O,O,O,O,O,O,O],
      [O,'e','w','w','w','e',O],
      [O,O,'w','n','w',O,O],
      [_,O,'w','w','w',O,_],
      [_,O,O,O,O,O,_],
      [_,_,O,_,O,_,_],
    ],
  },
  {
    name: 'pig',
    nameKo: '돼지',
    color: '#f8bbd0',
    pixels: [
      [_,O,O,O,O,O,_],
      [O,O,O,O,O,O,O],
      [O,'e',O,O,O,'e',O],
      [O,O,'n',O,'n',O,O],
      [O,O,'n','n','n',O,O],
      [_,O,O,O,O,O,_],
      [_,_,O,_,O,_,_],
    ],
  },
  {
    name: 'dragon',
    nameKo: '용',
    color: '#ab47bc',
    pixels: [
      [O,_,O,O,O,_,O],
      [O,O,O,O,O,O,O],
      [O,'e',O,O,O,'e',O],
      [O,O,O,O,O,O,O],
      [O,'n',O,O,O,'n',O],
      [_,O,O,O,O,O,_],
      [_,O,_,O,_,O,_],
    ],
  },
  {
    name: 'slime',
    nameKo: '슬라임',
    color: '#69f0ae',
    pixels: [
      [_,_,_,_,_,_,_],
      [_,_,O,O,O,_,_],
      [_,O,O,O,O,O,_],
      [O,O,'e',O,'e',O,O],
      [O,O,O,O,O,O,O],
      [O,O,O,O,O,O,O],
      [O,O,O,O,O,O,O],
    ],
  },
  {
    name: 'ghost',
    nameKo: '유령',
    color: '#e0e0e0',
    pixels: [
      [_,_,O,O,O,_,_],
      [_,O,O,O,O,O,_],
      [O,O,'e',O,'e',O,O],
      [O,O,O,O,O,O,O],
      [O,O,O,O,O,O,O],
      [O,O,O,O,O,O,O],
      [O,_,O,_,O,_,O],
    ],
  },
];
